version: '3.8'

services:
  data-warehouse:
    build: .
    container_name: financial-dw
    ports:
      - "8501:8501"
    volumes:
      
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1